### ISSUE TITLE
It should probably be possible to use nake functions without turning your file into a nakefile.

### ISSUE THREAD

**Issue by MrJohz** [fowlmouth/nake#19]
Currently, any program that imports nake becomes a nakefile due to the `moduleHook` quit proc.  While most uses of nake tools are going to simply going to be in nakefiles, someone may have a legitimate use for wanting to use convenience procs and templates such as `shell` and `withDir` without having to deal with the quit proc.

Solutions:

1. `moduleHook` should quit silently if there are no registered tasks.  (Currently it raises an error due to the requirement in the default list tasks implementation that the length of tasks should be greater than 0.)
2. A separate `nakelib.nim` module that can be imported.  All of the procs/etc in here should be imported into `nake.nim`, and re-exported, so that users who don't need to worry about this are fine, and for backwards compatibility, but it would be useful both for the above reasons, and also because modules are always fun.
3. A separate nakelib library that is maintained elsewhere.  Either nake then requires nakelib to run, or nakelib is maintained separately.
4. Do nothing.  Nake's functions aren't a library deliberately.

My vote would be for 2).  Does anyone else have an opinion on the matter?

**Comment by gradha** [comment]
Yes, [I can feel your pain](https://github.com/gradha/badger_bits/blob/master/tests/misc/test_misc.nim#L133). Option 2 looks safer to me on the long run. [Exported sections don't appear in the docs](https://github.com/Araq/Nim/issues/1616), but that shouldn't be much of a problem by including a manual redirection docstring in the main ``nake.nim`` file or telling people to go read directly ``nakelib.html``.
