### ISSUE TITLE
Add `()` alias for shell or direShell

### ISSUE THREAD

**Issue by gradha** [fowlmouth/nake#21]
Some time ago Araq wrote [a `()` alias](https://github.com/Araq/Nim/blob/3119fe087d28344a34f296f1548cd8d852aea2f8/tests/testament/backend.nim#L62) which makes shell execution look shorter. See if this doesn't have any other side effects and could be added to nake.

**Comment by fowlmouth** [comment]
ok with me

**Comment by yglukhov** [comment]
`()` support is now deprecated in nim. we should come up with something else.
