### ISSUE TITLE
Remove symbols deprecated in 1.6

### ISSUE THREAD

**Issue by gradha** [fowlmouth/nake#34]
This is a note for the future. Once nake 1.5 is released into a stable 1.6 version, the next development version should remove the symbols deprecated in #29. Since this breaks the API the newer version number should be bumped to 2.0 and noted appropriately in the changes log. To remind ourselves of this the development version could bump to 1.9 instead of 1.7.

**Comment by fowlmouth** [comment]
I don't think that is so much of an issue, only now is nakelib exposed to be usable from outside nake so there shouldn't be any code using PTask

**Comment by gradha** [comment]
True, it's hard to find nake users anyway.
