### ISSUE TITLE
nakelib raises unlisted exception IOError

### ISSUE THREAD

**Issue by fowlmouth** [fowlmouth/nake#38]
Affects 1.6, three procs need to add IOError

**Comment by gradha** [comment]
Works for me on OSX. Could this be a platform specific issue due to the rstdin module raising different exceptions on different platforms?

**Comment by gradha** [comment]
Tried nim-0.11.0 and still works for me. Tell me what platform this fix is for to mention it in the changes log.

**Comment by fowlmouth** [comment]
It does come from `readLineFromStdin` on windows, that function isn't marked with `{.raises.}` though as maybe it should be.

**Comment by gradha** [comment]
I'll release 1.8 tomorrow with the fix.

**Comment by gradha** [comment]
Starting release.
