### ISSUE TITLE
nake builds don't honoe LD_RUN_PATH

### ISSUE THREAD

**Issue by bkerin** [fowlmouth/nake#52]
With plain nim, generated binaries end up with a correct RPATH according to LD_RUN_PATH settings.
With nake this somehow doesn't happen (so for nimx I'm getting broken binaries because I have the latest version of SDL installed under my home dir, fixing RPATH with patchelf --set-rpath NimxApp makes the binary sample work).

I don't know if nake is honoring LIBRARY_PATH and CPATH but I doubt it.

Seems like if nim is going to honor these environment vars then nake maybe should too.

**Comment by yglukhov** [comment]
For now lets treat this as a duplicate of #53
